### ISSUE TITLE
首页顶部导航栏右侧的图标没显示

### ISSUE THREAD

**Issue by zanetti4** [xiaocheng555/vue3-jsx-shop#1]
我看到首页顶部导航栏 NavBar 使用了插槽，右侧内容写了两个图标：contact 和 search。但是启动项目后，这两个图标都没有显示，想问一下是什么原因？

**Comment by xiaocheng555** [comment]
你的信息已经收到了，祝你开心！！

**Comment by xiaocheng555** [comment]
是bug，NavBar组件里插槽需要从Proxy转为原始值

**Comment by xiaocheng555** [comment]
> 我看到首页顶部导航栏 NavBar 使用了插槽，右侧内容写了两个图标：contact 和 search。但是启动项目后，这两个图标都没有显示，想问一下是什么原因？

是bug，NavBar组件里插槽需要从Proxy转为原始值
![image](https://user-images.githubusercontent.com/19643785/188530733-c3a430b7-3572-40b5-891a-101980374699.png)

**Comment by zanetti4** [comment]
这个问题终于解决了，谢谢解答！

**Comment by xiaocheng555** [comment]
你的信息已经收到了，祝你开心--张焕城！！
